### ISSUE TITLE
rc 1.7.3 released?

### ISSUE THREAD

**Issue by chneukirchen** [TobyGoodwin/rc-pure-git#7]
Hi, I saw a tarball for 1.7.3 on your site, but there is no tag and no github release for it. Did you forget that or is that tarball preliminary?

**Comment by TobyGoodwin** [comment]
Hi Christian,

>Hi, I saw a tarball for 1.7.3 on your site, but there is no tag and no github release for it. Did you forget that or is that tarball preliminary?

It's preliminary, I wanted a few people (Jakub, Robert Scheck the new
Fedora maintainer, and Byron who has re-appeared) to check it over
before announcing it.

There aren't many changes, but I needed to wrap them up into a
tarball to test the Fedora installation. Also, with Byron's blessing,
the license has been tweaked slightly to be a "standard" FOSS one
(specifically: ZlibWithAcknowledgement).

If you want to test and report any issues, that would be welcome,
although anything non-trivial is likely to get pushed into 1.7.4. (Or it
may be 1.8... let's see. :-)

Cheers,

Toby.
